language: python
python:
	-"2.7"

install: "pip install -r requirements.txt"

before_script:
	-autopep8 -ir *
	-flake --max-complexity=3 --exclude=*.txt,*.md --max-line-length=200 *

script:
	-python NextDate.py -v
	-coverage run --branch NextDate.py
	-coverage report -m